global:
  scrape_interval: 15s

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['127.0.0.1:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['127.0.0.1:8080']
